### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by yurivict** [gamecreature/QtAwesome#42]
The last release was in 2015.

**Comment by gamecreature** [comment]
Hi @yurivict, I know it has been a while. 
I looked into it a few years ago. But since this v4 release (2015) Font-Awesome has been changed by adding categories like fas/far etc. Also there's a commercial part in the font definitions.

I don't see an easy way for QtAwesome to pickup this new format easy.  I want this library to be backwards compatible with  projects that are using this.

The idea I have for the future (but I didn't start with it), 
- Is to define a new project QtAwesome6? which includes the free (no commercial fonts) by default  
- And add a backwards compatibility layer so apps using the old font names still map to similar icons

**Comment by gamecreature** [comment]
I've been looking to the newer FontAwesome code. I think the code for QtAwesome6 cpp/h should be build dynamically by using the yaml/json files with meta information. This makes it much easier to keep the code up-to-date.

**Comment by gamecreature** [comment]
Font Awesome 6 version has been released 🎉

**Comment by yurivict** [comment]
@gamecreature There's only a 'fontawesome 6' comment, and no such tag in the repository.

**Comment by gamecreature** [comment]
Hi @yurivict what do you mean?
The new main branch contains the new release. Please note the master branch has been renamed to main.
Perhaps you cloned the repos while I was working on it. (I tried to add a main branch and keep the master. But that didn't go as well as I had imagined. So I choose the rename master to main branch later.)

**Comment by yurivict** [comment]
![image](https://user-images.githubusercontent.com/271906/209854739-067c72b6-53ef-4600-8f52-26096fd830b6.png)

**Comment by gamecreature** [comment]
Ah I see! 
I just tagged the latest 5 branch and the main branch:
- font-awesome-5.10.2
- font-awesome-6.2.0
